project:
  type: website
  output-dir: docs

website:
  title: "Precision Motion System"

format:
  revealjs:
    include-in-header:
      - include/password.html

    theme: [default, slides.scss]

    width: 1280
    height: 720
    margin: 0.1

    slide-number: true
    controls: false
    progress: true
    transition: none
    center: false

    footer: "Group C - Dipartimento di Ingegneria Industriale"

    pdf-max-pages-per-slide: 1
    pdf-separate-fragments: false

    embed-resources: true
    self-contained: true

    fig-width: 8
    fig-height: 4.5
    fig-dpi: 300
    
    logo: include/images/unitn_logo.png

execute:
  freeze: auto